<?php
/**
 * Button template
 *
 * @var $this Iparcel_CartHandoff_Block_Button
 */

$cartHandoff_hideCheckout = Mage::getStoreConfig('payment/ipcarthandoff/hide_proceed_to_checkout') ? 'true' : 'false';
$cartHandoff_hideOtherMethods = Mage::getStoreConfig('payment/ipcarthandoff/hide_other_checkout_methods') ? 'true' : 'false';
?>
<?php if ($this->shouldDisplay()): ?>
<p class="ipcarthandoff-button" style="<?php echo $this->getStyle() ?>">
    <a data-action="checkout-form-submit" href="<?php echo $this->getCheckoutUrl() ?>">
        <?php echo $this->getButtonTitle(); ?>
    </a>
</p>
<?php endif; ?>
<script type="text/javascript">
    cartHandoff_hideCheckout = <?php echo (string) $cartHandoff_hideCheckout; ?>;
    cartHandoff_hideOtherMethods = <?php echo (string) $cartHandoff_hideOtherMethods; ?>;
</script>
